printWidth: 80
tabWidth: 2
semi: false
useTabs: false
bracketSpacing: true
singleQuote: true
trailingComma: none
arrowParens: always
endOfLine: auto

plugins:
- "@trivago/prettier-plugin-sort-imports"

importOrder:
- "^react(.*)$"
- "^\\b(?!react\\b)(.*)$"
- "^@(.*)/?(.*)$"

