version: '3.10'

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build: ./backend
    command: python -m run
    env_file:
      - ./.env
    ports:
      - "8000:8000"