version: '3.8'

services:
  database:
    image: postgres
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    ports:
      - 5432:5432

  backend:
    build: ./backend
    container_name: backend
    command: poetry run app
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend:/app/backend
    external_links:
      - postgres:postgres
